# Generated by Django 5.2.7 on 2025-10-26 04:43

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PincodeUser',
            fields=[
            ],
            options={
                'verbose_name': 'Pincode User',
                'verbose_name_plural': 'Pincode Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
