# Generated by Django 5.2.7 on 2025-10-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pincodeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sponsor_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
