# Generated by Django 5.2.7 on 2025-10-27 07:57

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_sponsor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDistrict',
            fields=[
            ],
            options={
                'verbose_name': 'Agency District (TRD)',
                'verbose_name_plural': 'Agency Districts (TRD)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencyDistrictCoordinator',
            fields=[
            ],
            options={
                'verbose_name': 'Agency District Coordinator (TRDC)',
                'verbose_name_plural': 'Agency District Coordinators (TRDC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPincode',
            fields=[
            ],
            options={
                'verbose_name': 'Agency Pincode (TRP)',
                'verbose_name_plural': 'Agency Pincodes (TRP)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPincodeCoordinator',
            fields=[
            ],
            options={
                'verbose_name': 'Agency Pincode Coordinator (TRPC)',
                'verbose_name_plural': 'Agency Pincode Coordinators (TRPC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencyState',
            fields=[
            ],
            options={
                'verbose_name': 'Agency State (TRS)',
                'verbose_name_plural': 'Agency States (TRS)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencyStateCoordinator',
            fields=[
            ],
            options={
                'verbose_name': 'Agency State Coordinator (TRSC)',
                'verbose_name_plural': 'Agency State Coordinators (TRSC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgencySubFranchise',
            fields=[
            ],
            options={
                'verbose_name': 'Agency Sub-Franchise (TRSF)',
                'verbose_name_plural': 'Agency Sub-Franchises (TRSF)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Business (TRB)',
                'verbose_name_plural': 'Businesses (TRB)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Consumer (TRC)',
                'verbose_name_plural': 'Consumers (TRC)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Employee (TRE)',
                'verbose_name_plural': 'Employees (TRE)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('consumer', 'Consumer (General User)'), ('employee', 'Employee'), ('business', 'Business'), ('agency_state_coordinator', 'Agency State Coordinator'), ('agency_state', 'Agency State'), ('agency_district_coordinator', 'Agency District Coordinator'), ('agency_district', 'Agency District'), ('agency_pincode_coordinator', 'Agency Pincode Coordinator'), ('agency_pincode', 'Agency Pincode'), ('agency_sub_franchise', 'Agency Sub-Franchise')], default='consumer', max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True, null=True),
        ),
    ]
