# Generated by Django 5.2.7 on 2025-10-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agencydistrict_agencydistrictcoordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('consumer', 'Consumer (General User)'), ('employee', 'Employee'), ('business', 'Business'), ('agency_state_coordinator', 'Agency State Coordinator'), ('agency_state', 'Agency State'), ('agency_district_coordinator', 'Agency District Coordinator'), ('agency_district', 'Agency District'), ('agency_pincode_coordinator', 'Agency Pincode Coordinator'), ('agency_pincode', 'Agency Pincode'), ('agency_sub_franchise', 'Agency Sub-Franchise')], db_index=True, default='consumer', max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('agency', 'Agency'), ('employee', 'Employee')], db_index=True, default='user', max_length=20),
        ),
    ]
