# Generated by Django 5.2.7 on 2025-10-29 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_category_alter_customuser_pincode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessaccount',
            options={'verbose_name': 'Business Registration (TRB)', 'verbose_name_plural': 'Business Registrations (TRB)'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='forwarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_business_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('forwarded', 'Forwarded'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20),
        ),
    ]
