# Generated by Django 5.2.7 on 2025-10-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_businessaccount_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessAccount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='forwarded_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='forwarded_to',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='review_status',
        ),
    ]
