# Generated by Django 5.2.7 on 2025-10-29 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_businessaccount_and_more'),
        ('locations', '0004_remove_country_iso3_alter_country_iso2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRegionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('state', 'State'), ('district', 'District'), ('pincode', 'Pincode')], db_index=True, max_length=16)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_assignments', to='locations.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'level'], name='accounts_ag_user_id_d6b31c_idx'), models.Index(fields=['level', 'state'], name='accounts_ag_level_c7917d_idx'), models.Index(fields=['level', 'pincode'], name='accounts_ag_level_21977d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('level', 'state')), fields=('user', 'level', 'state'), name='uniq_assignment_user_state'), models.UniqueConstraint(condition=models.Q(('level', 'district')), fields=('user', 'state', 'district', 'level'), name='uniq_assignment_user_state_district_ci'), models.UniqueConstraint(condition=models.Q(('level', 'pincode')), fields=('user', 'level', 'pincode'), name='uniq_assignment_user_pincode')],
            },
        ),
    ]
