# Generated by Django 5.2.7 on 2025-10-29 18:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_agencyregionassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('consumer', 'Consumer (General User)'), ('employee', 'Employee'), ('business', 'Business'), ('company', 'Company'), ('agency_state_coordinator', 'Agency State Coordinator'), ('agency_state', 'Agency State'), ('agency_district_coordinator', 'Agency District Coordinator'), ('agency_district', 'Agency District'), ('agency_pincode_coordinator', 'Agency Pincode Coordinator'), ('agency_pincode', 'Agency Pincode'), ('agency_sub_franchise', 'Agency Sub-Franchise')], db_index=True, default='consumer', max_length=40),
        ),
    ]
