# Generated by Django 5.2.7 on 2025-10-30 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_companyaccount_alter_customuser_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('COUPON_PURCHASE_CREDIT', 'Coupon Purchase Credit'), ('REDEEM_ECOUPON_CREDIT', 'E-Coupon Redeem Credit'), ('PRODUCT_PURCHASE_DEBIT', 'Product Purchase Debit'), ('COMMISSION_CREDIT', 'Commission Credit'), ('AUTO_POOL_DEBIT', 'Auto Pool Debit'), ('ADJUSTMENT_CREDIT', 'Adjustment Credit'), ('ADJUSTMENT_DEBIT', 'Adjustment Debit'), ('REFUND_CREDIT', 'Refund Credit')], db_index=True, max_length=32)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='accounts_wa_user_id_707ea0_idx'), models.Index(fields=['created_at'], name='accounts_wa_created_0b5359_idx')],
            },
        ),
    ]
