# Generated by Django 5.2.7 on 2025-10-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencydistrict',
            options={'verbose_name': 'Agency District', 'verbose_name_plural': 'Agency Districts'},
        ),
        migrations.AlterModelOptions(
            name='agencydistrictcoordinator',
            options={'verbose_name': 'Agency District Coordinator', 'verbose_name_plural': 'Agency District Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='agencypincode',
            options={'verbose_name': 'Agency Pincode', 'verbose_name_plural': 'Agency Pincodes'},
        ),
        migrations.AlterModelOptions(
            name='agencypincodecoordinator',
            options={'verbose_name': 'Agency Pincode Coordinator', 'verbose_name_plural': 'Agency Pincode Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='agencystate',
            options={'verbose_name': 'Agency State', 'verbose_name_plural': 'Agency States'},
        ),
        migrations.AlterModelOptions(
            name='agencystatecoordinator',
            options={'verbose_name': 'Agency State Coordinator', 'verbose_name_plural': 'Agency State Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='agencysubfranchise',
            options={'verbose_name': 'Agency Sub-Franchise', 'verbose_name_plural': 'Agency Sub-Franchises'},
        ),
        migrations.AlterModelOptions(
            name='consumeraccount',
            options={'verbose_name': 'Consumer', 'verbose_name_plural': 'Consumers'},
        ),
        migrations.AlterModelOptions(
            name='employeeaccount',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
