# Generated by Django 5.2.7 on 2025-11-03 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_agencydistrict_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('COUPON_PURCHASE_CREDIT', 'Coupon Purchase Credit'), ('REDEEM_ECOUPON_CREDIT', 'E-Coupon Redeem Credit'), ('PRODUCT_PURCHASE_DEBIT', 'Product Purchase Debit'), ('BANNER_PURCHASE_DEBIT', 'Banner Purchase Debit'), ('COMMISSION_CREDIT', 'Commission Credit'), ('AUTO_POOL_DEBIT', 'Auto Pool Debit'), ('ADJUSTMENT_CREDIT', 'Adjustment Credit'), ('ADJUSTMENT_DEBIT', 'Adjustment Debit'), ('REFUND_CREDIT', 'Refund Credit'), ('PRIME_ACTIVATION_CREDIT', 'Prime Activation Credit'), ('GLOBAL_ACTIVATION_CREDIT', 'Global Activation Credit'), ('DIRECT_REF_BONUS', 'Direct Referral Bonus'), ('WELCOME_BONUS', 'Welcome Bonus'), ('SELF_BONUS_ACTIVE', 'Self Bonus (Active)'), ('LEVEL_BONUS', 'Level Bonus'), ('AUTOPOOL_BONUS_FIVE', 'Auto-Pool Bonus (5-Matrix)'), ('AUTOPOOL_BONUS_THREE', 'Auto-Pool Bonus (3-Matrix)'), ('WITHDRAWAL_DEBIT', 'Withdrawal Debit'), ('LIFETIME_WITHDRAWAL_BONUS', 'Lifetime Withdrawal Bonus'), ('GLOBAL_ROYALTY', 'Global Royalty'), ('REWARD_CREDIT', 'Reward Credit'), ('REWARD_DEBIT', 'Reward Debit')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='UserKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verified_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User KYC',
                'verbose_name_plural': 'User KYC',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('upi', 'UPI'), ('bank', 'Bank Transfer')], db_index=True, default='upi', max_length=16)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('payout_ref', models.CharField(blank=True, max_length=100)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_decided', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_wi_user_id_8764b0_idx'), models.Index(fields=['status', 'requested_at'], name='accounts_wi_status_b7396b_idx')],
            },
        ),
    ]
