# Generated by Django 5.2.7 on 2025-11-08 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_address_customuser_avatar'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0004_remove_country_iso3_alter_country_iso2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='depth',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='matrix_position',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['parent'], name='accounts_cu_parent__6eb00d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['depth'], name='accounts_cu_depth_a5ba98_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'matrix_position'), name='uniq_parent_matrix_position'),
        ),
    ]
