# Generated by Django 5.2.7 on 2025-11-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefixSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('last_number', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prefix Sequence',
                'verbose_name_plural': 'Prefix Sequences',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='prefix_code',
            field=models.CharField(blank=True, db_index=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prefixed_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
