# Generated by Django 5.2.7 on 2025-11-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_prefixsequence_customuser_prefix_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('consumer', 'Consumer (General User)'), ('employee', 'Employee'), ('business', 'Business'), ('company', 'Company'), ('agency_state_coordinator', 'Agency State Coordinator'), ('agency_state', 'Agency State'), ('agency_district_coordinator', 'Agency District Coordinator'), ('agency_district', 'Agency District'), ('agency_pincode_coordinator', 'Agency Pincode Coordinator'), ('agency_pincode', 'Agency Pincode'), ('agency_sub_franchise', 'Agency Sub-Franchise'), ('company_manager', 'Company Manager')], db_index=True, default='consumer', max_length=40),
        ),
    ]
