# Generated by Django 5.2.7 on 2025-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_wallet_main_balance_wallet_withdrawable_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
