# Generated by Django 5.2.7 on 2025-11-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_customuser_last_password_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
