# Generated by Django 5.2.7 on 2025-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_customuser_account_active'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0004_remove_country_iso3_alter_country_iso2'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='accounts_cu_date_jo_fcefff_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['account_active', 'date_joined'], name='accounts_cu_account_0b50cf_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['first_purchase_activated_at'], name='accounts_cu_first_p_d0a76b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'category'], name='accounts_cu_role_b56f08_idx'),
        ),
    ]
