# Generated by Django 5.2.7 on 2025-12-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_customuser_accounts_cu_date_jo_fcefff_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('COUPON_PURCHASE_CREDIT', 'Coupon Purchase Credit'), ('REDEEM_ECOUPON_CREDIT', 'E-Coupon Redeem Credit'), ('PRODUCT_PURCHASE_DEBIT', 'Product Purchase Debit'), ('BANNER_PURCHASE_DEBIT', 'Banner Purchase Debit'), ('COMMISSION_CREDIT', 'Commission Credit'), ('AUTO_POOL_DEBIT', 'Auto Pool Debit'), ('ADJUSTMENT_CREDIT', 'Adjustment Credit'), ('ADJUSTMENT_DEBIT', 'Adjustment Debit'), ('REFUND_CREDIT', 'Refund Credit'), ('PRIME_ACTIVATION_CREDIT', 'Prime Activation Credit'), ('GLOBAL_ACTIVATION_CREDIT', 'Global Activation Credit'), ('DIRECT_REF_BONUS', 'Direct Referral Bonus'), ('WELCOME_BONUS', 'Welcome Bonus'), ('SELF_BONUS_ACTIVE', 'Self Bonus (Active)'), ('LEVEL_BONUS', 'Level Bonus'), ('AUTOPOOL_BONUS_FIVE', 'Auto-Pool Bonus (5-Matrix)'), ('AUTOPOOL_BONUS_THREE', 'Auto-Pool Bonus (3-Matrix)'), ('WITHDRAWAL_DEBIT', 'Withdrawal Debit'), ('LIFETIME_WITHDRAWAL_BONUS', 'Lifetime Withdrawal Bonus'), ('GLOBAL_ROYALTY', 'Global Royalty'), ('REWARD_CREDIT', 'Reward Credit'), ('REWARD_DEBIT', 'Reward Debit'), ('FRANCHISE_INCOME', 'Franchise Income'), ('WITHDRAWABLE_CREDIT', 'Withdrawable Credit'), ('TAX_POOL_CREDIT', 'Tax Pool Credit'), ('ECOUPON_WALLET_DEBIT', 'E-Coupon Wallet Debit'), ('AUTO_PURCHASE_DEBIT', 'Auto Purchase Debit'), ('PRODUCT_WALLET_CREDIT', 'Product Wallet Credit')], db_index=True, max_length=32),
        ),
    ]
