# Generated by Django 5.2.7 on 2025-12-20 14:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_userkyc_aadhaar_digilocker_url_usernominee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('consumer', 'Consumer (General User)'), ('employee', 'Employee'), ('business', 'Business'), ('merchant', 'Merchant'), ('company', 'Company'), ('agency_state_coordinator', 'Agency State Coordinator'), ('agency_state', 'Agency State'), ('agency_district_coordinator', 'Agency District Coordinator'), ('agency_district', 'Agency District'), ('agency_pincode_coordinator', 'Agency Pincode Coordinator'), ('agency_pincode', 'Agency Pincode'), ('agency_sub_franchise', 'Agency Sub-Franchise'), ('company_manager', 'Company Manager')], db_index=True, default='consumer', max_length=40),
        ),
        migrations.CreateModel(
            name='RewardPointsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_points_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='accounts_re_user_id_30ccce_idx')],
            },
        ),
        migrations.CreateModel(
            name='RewardPointsHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('RELEASED', 'Released')], db_index=True, default='PENDING', max_length=16)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_points_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_re_user_id_d75c52_idx'), models.Index(fields=['source_type', 'source_id'], name='accounts_re_source__b54189_idx')],
            },
        ),
        migrations.CreateModel(
            name='RewardPointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem'), ('ADJUST', 'Adjust')], db_index=True, max_length=16)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='accounts_re_user_id_a858c0_idx'), models.Index(fields=['created_at'], name='accounts_re_created_a5e251_idx')],
            },
        ),
    ]
