# Generated by Django 6.0.1 on 2026-01-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_compound_indexes_users'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='cu_regby_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='cu_pin_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='cu_role_cat_date_idx',
        ),
    ]
