# Generated by Django 5.2.10 on 2026-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_customuser_cu_regby_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='uploads/profile/'),
        ),
    ]
