# Generated by Django 5.2.10 on 2026-04-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0033_commissionconfig_withdrawals_window"),
        ("accounts", "0035_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="matrix_account",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="business.autopoolaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(fields=["user", "matrix_account"], name="wtx_user_matrix_idx"),
        ),
    ]
