# Generated by Django 6.0.2 on 2026-04-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_wallettransaction_matrix_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='accounts_wa_user_id_166971_idx',
            old_name='wtx_user_matrix_idx',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('COUPON_PURCHASE_CREDIT', 'Coupon Purchase Credit'), ('REDEEM_ECOUPON_CREDIT', 'E-Coupon Redeem Credit'), ('PRODUCT_PURCHASE_DEBIT', 'Product Purchase Debit'), ('BANNER_PURCHASE_DEBIT', 'Banner Purchase Debit'), ('COMMISSION_CREDIT', 'Commission Credit'), ('AUTO_POOL_DEBIT', 'Auto Pool Debit'), ('ADJUSTMENT_CREDIT', 'Adjustment Credit'), ('ADJUSTMENT_DEBIT', 'Adjustment Debit'), ('REFUND_CREDIT', 'Refund Credit'), ('PRIME_ACTIVATION_CREDIT', 'Prime Activation Credit'), ('GLOBAL_ACTIVATION_CREDIT', 'Global Activation Credit'), ('DIRECT_REF_BONUS', 'Direct Referral Bonus'), ('WELCOME_BONUS', 'Welcome Bonus'), ('SELF_BONUS_ACTIVE', 'Self Bonus (Active)'), ('LEVEL_BONUS', 'Level Bonus'), ('AUTOPOOL_BONUS_FIVE', 'Auto-Pool Bonus (5-Matrix)'), ('AUTOPOOL_BONUS_THREE', 'Auto-Pool Bonus (3-Matrix)'), ('WITHDRAWAL_DEBIT', 'Withdrawal Debit'), ('LIFETIME_WITHDRAWAL_BONUS', 'Lifetime Withdrawal Bonus'), ('GLOBAL_ROYALTY', 'Global Royalty'), ('REWARD_CREDIT', 'Reward Credit'), ('REWARD_DEBIT', 'Reward Debit'), ('FRANCHISE_INCOME', 'Franchise Income'), ('WITHDRAWABLE_CREDIT', 'Withdrawable Credit'), ('TAX_POOL_CREDIT', 'Tax Pool Credit'), ('ECOUPON_WALLET_DEBIT', 'E-Coupon Wallet Debit'), ('AUTO_PURCHASE_DEBIT', 'Auto Purchase Debit'), ('PRODUCT_WALLET_CREDIT', 'Product Wallet Credit'), ('SHOPPING_WALLET_CREDIT', 'Shopping Wallet Credit'), ('SHOPPING_WALLET_DEBIT', 'Shopping Wallet Debit'), ('SHOPPING_WALLET_TRANSFER_OUT', 'Shopping Wallet Transfer Out'), ('INTERNAL_WALLET_CREDIT', 'Internal Wallet Credit'), ('INTERNAL_WALLET_DEBIT', 'Internal Wallet Debit'), ('INTERNAL_WALLET_TRANSFER_OUT', 'Internal Wallet Transfer Out'), ('WALLET_TO_WALLET_IN', 'Wallet To Wallet In'), ('WALLET_TO_WALLET_OUT', 'Wallet To Wallet Out'), ('WITHDRAWAL_WALLET_TRANSFER_OUT', 'Withdrawal Wallet Transfer Out'), ('WITHDRAWAL_WALLET_CREDIT', 'Withdrawal Wallet Credit'), ('INCOME_CREDIT_75', 'Income Credit'), ('SELF_ACCOUNT_CREDIT', 'Self Account Credit'), ('SELF_ACCOUNT_DEBIT', 'Self Account Debit (250 Pack)'), ('AUTO_ECOUPON_ISSUED', 'Auto E-Coupon Issued')], db_index=True, max_length=32),
        ),
    ]
