# Generated by Django 6.0.2 on 2026-05-03 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_rename_wtx_user_matrix_idx_accounts_wa_user_id_166971_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletUploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utr', models.CharField(db_index=True, max_length=64)),
                ('proof', models.FileField(blank=True, null=True, upload_to='wallet_uploads/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={},
        ),
        migrations.AddField(
            model_name='walletuploadrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_upload_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletuploadrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_upload_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletuploadrequest',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_upload_requests', to='accounts.wallettransaction'),
        ),
        migrations.AddIndex(
            model_name='walletuploadrequest',
            index=models.Index(fields=['status', 'requested_at'], name='wul_status_req_idx'),
        ),
        migrations.AddIndex(
            model_name='walletuploadrequest',
            index=models.Index(fields=['user', 'status'], name='wul_user_status_idx'),
        ),
    ]
