# Generated by Django 6.0.2 on 2026-05-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_identity_type(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    admin_q = models.Q(is_staff=True) | models.Q(is_superuser=True)
    User.objects.filter(admin_q).update(identity_type='ADMIN')
    User.objects.exclude(admin_q).update(identity_type='END_USER')


def backfill_user_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'CustomUser')
    UserRole = apps.get_model('adminapi', 'UserRole')
    links = []
    for user in User.objects.exclude(admin_role_id__isnull=True).only('id', 'admin_role_id'):
        links.append(UserRole(user_id=user.id, role_id=user.admin_role_id))
    if links:
        UserRole.objects.bulk_create(links, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_walletuploadrequest_alter_wallettransaction_options_and_more'),
        ('adminapi', '0002_permission_module_permission_name_role_description_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0004_remove_country_iso3_alter_country_iso2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('END_USER', 'End User'), ('ADMIN', 'Admin')], db_index=True, max_length=20)),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'password_reset_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin_roles',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', through='adminapi.UserRole', to='adminapi.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_type',
            field=models.CharField(choices=[('END_USER', 'End User'), ('ADMIN', 'Admin')], db_index=True, default='END_USER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['identity_type', 'is_staff'], name='accounts_cu_identit_6482ac_idx'),
        ),
        migrations.RunPython(backfill_identity_type, migrations.RunPython.noop),
        migrations.RunPython(backfill_user_roles, migrations.RunPython.noop),
        migrations.AddField(
            model_name='auditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_user', 'action'], name='audit_logs_actor_u_002b35_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'identity_type', 'is_used'], name='password_re_user_id_b2202d_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['expires_at', 'is_used'], name='password_re_expires_be3b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['ip_address', 'created_at'], name='password_re_ip_addr_da5c4d_idx'),
        ),
    ]
