# Generated by Django 6.0.2 on 2026-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auditlog_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='purpose',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('ADMIN_LOGIN', 'Admin Login')], db_index=True, default='PASSWORD_RESET', max_length=32),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'identity_type', 'purpose', 'is_used'], name='password_re_user_id_28f1b4_idx'),
        ),
    ]
