# Generated by Codex on 2026-05-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_remove_wallettransaction_accounts_wa_user_id_707ea0_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("COUPON_PURCHASE_CREDIT", "Coupon Purchase Credit"),
                    ("REDEEM_ECOUPON_CREDIT", "E-Coupon Redeem Credit"),
                    ("PRODUCT_PURCHASE_DEBIT", "Product Purchase Debit"),
                    ("BANNER_PURCHASE_DEBIT", "Banner Purchase Debit"),
                    ("COMMISSION_CREDIT", "Commission Credit"),
                    ("AUTO_POOL_DEBIT", "Auto Pool Debit"),
                    ("ADJUSTMENT_CREDIT", "Adjustment Credit"),
                    ("ADJUSTMENT_DEBIT", "Adjustment Debit"),
                    ("REFUND_CREDIT", "Refund Credit"),
                    ("PRIME_ACTIVATION_CREDIT", "Prime Activation Credit"),
                    ("GLOBAL_ACTIVATION_CREDIT", "Global Activation Credit"),
                    ("DIRECT_REF_BONUS", "Direct Referral Bonus"),
                    ("WELCOME_BONUS", "Welcome Bonus"),
                    ("SELF_BONUS_ACTIVE", "Self Bonus (Active)"),
                    ("LEVEL_BONUS", "Level Bonus"),
                    ("AUTOPOOL_BONUS_FIVE", "Auto-Pool Bonus (5-Matrix)"),
                    ("AUTOPOOL_BONUS_THREE", "Auto-Pool Bonus (3-Matrix)"),
                    ("WITHDRAWAL_DEBIT", "Withdrawal Debit"),
                    ("LIFETIME_WITHDRAWAL_BONUS", "Lifetime Withdrawal Bonus"),
                    ("GLOBAL_ROYALTY", "Global Royalty"),
                    ("REWARD_CREDIT", "Reward Credit"),
                    ("REWARD_DEBIT", "Reward Debit"),
                    ("FRANCHISE_INCOME", "Franchise Income"),
                    ("WITHDRAWABLE_CREDIT", "Withdrawable Credit"),
                    ("TAX_POOL_CREDIT", "Tax Pool Credit"),
                    ("ECOUPON_WALLET_DEBIT", "E-Coupon Wallet Debit"),
                    ("AUTO_PURCHASE_DEBIT", "Auto Purchase Debit"),
                    ("PRODUCT_WALLET_CREDIT", "Product Wallet Credit"),
                    ("SHOPPING_WALLET_CREDIT", "Shopping Wallet Credit"),
                    ("SHOPPING_WALLET_DEBIT", "Shopping Wallet Debit"),
                    ("SHOPPING_WALLET_TRANSFER_OUT", "Shopping Wallet Transfer Out"),
                    ("COUPON_WALLET_CREDIT", "Coupon Wallet Credit"),
                    ("COUPON_WALLET_DEBIT", "Coupon Wallet Debit"),
                    ("COUPON_WALLET_TRANSFER_OUT", "Coupon Wallet Transfer Out"),
                    ("COUPON_WALLET_REFUND", "Coupon Wallet Refund"),
                    ("PACKAGE_COUPON_WALLET_CREDIT", "Package Coupon Wallet Credit"),
                    ("PACKAGE_COUPON_WALLET_DEBIT", "Package Coupon Wallet Debit"),
                    ("VOUCHER_CREATE_DEBIT", "Voucher Create Debit"),
                    ("VOUCHER_REDEEM_CREDIT", "Voucher Redeem Credit"),
                    ("INTERNAL_WALLET_CREDIT", "Internal Wallet Credit"),
                    ("INTERNAL_WALLET_DEBIT", "Internal Wallet Debit"),
                    ("INTERNAL_WALLET_TRANSFER_OUT", "Internal Wallet Transfer Out"),
                    ("WALLET_TO_WALLET_IN", "Wallet To Wallet In"),
                    ("WALLET_TO_WALLET_OUT", "Wallet To Wallet Out"),
                    ("WITHDRAWAL_WALLET_TRANSFER_OUT", "Withdrawal Wallet Transfer Out"),
                    ("WITHDRAWAL_WALLET_CREDIT", "Withdrawal Wallet Credit"),
                    ("INCOME_CREDIT_75", "Income Credit"),
                    ("SELF_ACCOUNT_CREDIT", "Self Account Credit"),
                    ("SELF_ACCOUNT_DEBIT", "Self Account Debit (250 Pack)"),
                    ("AUTO_ECOUPON_ISSUED", "Auto E-Coupon Issued"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ConsumerVoucher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("TRIZONE", "Trizone Voucher"),
                            ("ONLINE", "Online Coupon"),
                            ("NEAR_STORE", "Near Store Coupon"),
                            ("PACKAGE_PURCHASE", "Package Purchase Coupon"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REDEEMED", "Redeemed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional intended redeemer, mainly for package purchase coupons.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_consumer_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_consumer_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debit_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voucher_debits",
                        to="accounts.wallettransaction",
                    ),
                ),
                (
                    "redeem_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voucher_redeems",
                        to="accounts.wallettransaction",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redeemed_consumer_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "refund_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voucher_refunds",
                        to="accounts.wallettransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="consumervoucher",
            index=models.Index(fields=["creator", "status"], name="cv_creator_status_idx"),
        ),
        migrations.AddIndex(
            model_name="consumervoucher",
            index=models.Index(fields=["assigned_to", "status"], name="cv_assignee_status_idx"),
        ),
        migrations.AddIndex(
            model_name="consumervoucher",
            index=models.Index(fields=["voucher_type", "status"], name="cv_type_status_idx"),
        ),
    ]
