# State-only migration for Django-generated index-name drift.
#
# These changes were generated by makemigrations after model edits elsewhere,
# but applying them as database operations can fail when the live database has
# already diverged in physical index names. This updates Django's migration
# state only and leaves the database untouched.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_financial_transaction_ledger"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="wallettransaction",
                    name="accounts_wa_user_id_707ea0_idx",
                ),
                migrations.RemoveIndex(
                    model_name="wallettransaction",
                    name="accounts_wa_created_0b5359_idx",
                ),
                migrations.RemoveIndex(
                    model_name="wallettransaction",
                    name="accounts_wa_user_id_166971_idx",
                ),
                migrations.RenameIndex(
                    model_name="financialtransaction",
                    new_name="accounts_fi_categor_646034_idx",
                    old_name="accounts_fi_categor_2c0c1a_idx",
                ),
                migrations.RenameIndex(
                    model_name="financialtransaction",
                    new_name="accounts_fi_source__e5571f_idx",
                    old_name="accounts_fi_source__1a4780_idx",
                ),
                migrations.RenameIndex(
                    model_name="financialtransaction",
                    new_name="accounts_fi_user_id_52507b_idx",
                    old_name="accounts_fi_user_id_55b4f3_idx",
                ),
                migrations.RenameIndex(
                    model_name="financialtransaction",
                    new_name="accounts_fi_approva_69d1cb_idx",
                    old_name="accounts_fi_approva_df1d05_idx",
                ),
                migrations.RenameIndex(
                    model_name="financialtransaction",
                    new_name="accounts_fi_flow_id_398e3d_idx",
                    old_name="accounts_fi_flow_id_8a45cc_idx",
                ),
                migrations.RenameIndex(
                    model_name="ledgerentry",
                    new_name="accounts_le_wallet__7579de_idx",
                    old_name="accounts_le_wallet_464d24_idx",
                ),
                migrations.RenameIndex(
                    model_name="ledgerentry",
                    new_name="accounts_le_financi_e448a2_idx",
                    old_name="accounts_le_financi_2f1cfa_idx",
                ),
                migrations.RenameIndex(
                    model_name="ledgerentry",
                    new_name="accounts_le_user_id_3c4a94_idx",
                    old_name="accounts_le_user_id_29d645_idx",
                ),
                migrations.RenameIndex(
                    model_name="ledgerentry",
                    new_name="accounts_le_status_88a0fe_idx",
                    old_name="accounts_le_status_51ce7f_idx",
                ),
                migrations.RenameIndex(
                    model_name="walletaccount",
                    new_name="accounts_wa_wallet__53cf8a_idx",
                    old_name="accounts_wa_wallet_70de35_idx",
                ),
                migrations.RenameIndex(
                    model_name="walletaccount",
                    new_name="accounts_wa_user_id_b023e6_idx",
                    old_name="accounts_wa_user_id_5fc05d_idx",
                ),
            ],
        ),
    ]
