# Generated by Django 6.0.2 on 2026-08-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_franchise_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='main_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='self_account_balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='withdrawable_balance',
        ),
    ]
