# Generated by Cline for mlm_ranks initial schema (new app only)
from django.conf import settings
from django.db import migrations, models
import decimal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('level_number', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('team_size_required', models.PositiveIntegerField(default=0)),
                ('upgrade_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.AddIndex(
            model_name='rank',
            index=models.Index(fields=['level_number'], name='mlm_ranks_ra_level_n_b7aab1_idx'),
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('total_team_size', models.PositiveIntegerField(default=0)),
                ('direct_count', models.PositiveIntegerField(default=0)),
                ('current_rank', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='holders', to='mlm_ranks.rank')),
                ('user', models.OneToOneField(db_index=True, on_delete=models.deletion.CASCADE, related_name='rank_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userrank',
            index=models.Index(fields=['user'], name='mlm_ranks_us_user_id_b5a3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='userrank',
            index=models.Index(fields=['current_rank'], name='mlm_ranks_us_current_9e6a01_idx'),
        ),
        migrations.CreateModel(
            name='RankUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('INITIATED', 'INITIATED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='INITIATED', max_length=16)),
                ('upgraded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_rank', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='from_upgrades', to='mlm_ranks.rank')),
                ('to_rank', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='to_upgrades', to='mlm_ranks.rank')),
                ('user', models.ForeignKey(db_index=True, on_delete=models.deletion.CASCADE, related_name='rank_upgrades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='rankupgrade',
            index=models.Index(fields=['user', 'created_at'], name='mlm_ranks_ra_user_id__f2b86c_idx'),
        ),
        migrations.AddIndex(
            model_name='rankupgrade',
            index=models.Index(fields=['payment_status'], name='mlm_ranks_ra_payment_b4d643_idx'),
        ),
        migrations.AddIndex(
            model_name='rankupgrade',
            index=models.Index(fields=['to_rank'], name='mlm_ranks_ra_to_rank_62f4e7_idx'),
        ),
        migrations.CreateModel(
            name='UpgradeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('commission_type', models.CharField(choices=[('DIRECT', 'DIRECT'), ('LEVEL', 'LEVEL')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CREDITED', 'CREDITED'), ('HELD', 'HELD'), ('FORFEITED_TO_COMPANY', 'FORFEITED_TO_COMPANY')], db_index=True, default='PENDING', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='upgrade_commissions_origin', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(db_index=True, on_delete=models.deletion.CASCADE, related_name='upgrade_commissions_target', to=settings.AUTH_USER_MODEL)),
                ('upgrade', models.ForeignKey(db_index=True, on_delete=models.deletion.CASCADE, related_name='commissions', to='mlm_ranks.rankupgrade')),
            ],
            options={
                'ordering': ['upgrade_id', 'level', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='upgradecommission',
            index=models.Index(fields=['to_user', 'status'], name='mlm_ranks_up_to_user__9451a9_idx'),
        ),
        migrations.AddIndex(
            model_name='upgradecommission',
            index=models.Index(fields=['upgrade', 'level'], name='mlm_ranks_up_upgrade__2f4006_idx'),
        ),
        migrations.AddIndex(
            model_name='upgradecommission',
            index=models.Index(fields=['commission_type', 'status'], name='mlm_ranks_up_commiss_5f6f0b_idx'),
        ),
        migrations.CreateModel(
            name='CommissionHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('release_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RELEASED', 'RELEASED'), ('FORFEITED_TO_COMPANY', 'FORFEITED_TO_COMPANY')], db_index=True, default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission', models.OneToOneField(db_index=True, on_delete=models.deletion.CASCADE, related_name='hold', to='mlm_ranks.upgradecommission')),
            ],
            options={
                'ordering': ['release_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='commissionhold',
            index=models.Index(fields=['status', 'release_date'], name='mlm_ranks_co_status__3f8287_idx'),
        ),
    ]
