# Generated by Django 6.0.1 on 2026-02-10 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlm_ranks', '0002_seed_ranks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissionhold',
            new_name='mlm_ranks_c_status_4d0bf0_idx',
            old_name='mlm_ranks_co_status__3f8287_idx',
        ),
        migrations.RenameIndex(
            model_name='rank',
            new_name='mlm_ranks_r_level_n_c93299_idx',
            old_name='mlm_ranks_ra_level_n_b7aab1_idx',
        ),
        migrations.RenameIndex(
            model_name='rankupgrade',
            new_name='mlm_ranks_r_user_id_81c1f6_idx',
            old_name='mlm_ranks_ra_user_id__f2b86c_idx',
        ),
        migrations.RenameIndex(
            model_name='rankupgrade',
            new_name='mlm_ranks_r_payment_f02341_idx',
            old_name='mlm_ranks_ra_payment_b4d643_idx',
        ),
        migrations.RenameIndex(
            model_name='rankupgrade',
            new_name='mlm_ranks_r_to_rank_2775dd_idx',
            old_name='mlm_ranks_ra_to_rank_62f4e7_idx',
        ),
        migrations.RenameIndex(
            model_name='upgradecommission',
            new_name='mlm_ranks_u_to_user_1365b9_idx',
            old_name='mlm_ranks_up_to_user__9451a9_idx',
        ),
        migrations.RenameIndex(
            model_name='upgradecommission',
            new_name='mlm_ranks_u_upgrade_f4dd9e_idx',
            old_name='mlm_ranks_up_upgrade__2f4006_idx',
        ),
        migrations.RenameIndex(
            model_name='upgradecommission',
            new_name='mlm_ranks_u_commiss_df9853_idx',
            old_name='mlm_ranks_up_commiss_5f6f0b_idx',
        ),
        migrations.RenameIndex(
            model_name='userrank',
            new_name='mlm_ranks_u_user_id_d7300f_idx',
            old_name='mlm_ranks_us_user_id_b5a3c2_idx',
        ),
        migrations.RenameIndex(
            model_name='userrank',
            new_name='mlm_ranks_u_current_af104d_idx',
            old_name='mlm_ranks_us_current_9e6a01_idx',
        ),
    ]
