# Generated by Django 5.2.10 on 2026-02-10 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm_ranks', '0003_rename_mlm_ranks_co_status__3f8287_idx_mlm_ranks_c_status_4d0bf0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankUpgradePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='rank_payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mlm_ranks.rankupgrade')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['upgrade', 'created_at'], name='mlm_ranks_r_upgrade_b3af50_idx')],
            },
        ),
    ]
