# Generated by Django 5.2.7 on 2026-02-11 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm_ranks', '0004_rankupgradepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankMatrixNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(db_index=True)),
                ('approved_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('placed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_matrix_as_child', to=settings.AUTH_USER_MODEL)),
                ('root_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_matrix_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['approved_at', 'position', 'id'],
                'indexes': [models.Index(fields=['root_user', 'position'], name='mlm_ranks_r_root_us_b9bebf_idx'), models.Index(fields=['root_user', 'placed_user'], name='mlm_ranks_r_root_us_fa4a24_idx')],
                'unique_together': {('root_user', 'placed_user'), ('root_user', 'position')},
            },
        ),
        migrations.CreateModel(
            name='RankMatrixRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_upgrade_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expiry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_roots', to='mlm_ranks.rank')),
                ('root_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_matrix_roots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['root_user'], name='mlm_ranks_r_root_us_a8a4b9_idx'), models.Index(fields=['rank'], name='mlm_ranks_r_rank_id_484953_idx'), models.Index(fields=['first_upgrade_at'], name='mlm_ranks_r_first_u_53b712_idx'), models.Index(fields=['expiry_at'], name='mlm_ranks_r_expiry__870210_idx')],
                'unique_together': {('root_user', 'rank')},
            },
        ),
    ]
