# Generated by Django 6.0.2 on 2026-04-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm_ranks', '0006_rankmatrixnode_parent_leveldepth'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rankmatrixnode',
            name='mlm_ranks_r_root_us_b9bebf_idx',
        ),
        migrations.RenameIndex(
            model_name='rankmatrixnode',
            new_name='mlm_ranks_r_root_us_935b71_idx',
            old_name='mx_idx_root_parent_pos',
        ),
        migrations.RenameIndex(
            model_name='rankmatrixnode',
            new_name='mlm_ranks_r_root_us_53a023_idx',
            old_name='mx_idx_root_level',
        ),
        migrations.AlterField(
            model_name='rankmatrixnode',
            name='level_depth',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
