"""
Reconcile matrices using the analysis CSV generated by analyze_promo_matrix_expectations.py
Deletes extra FIVE_150/THREE_150 accounts per user while keeping earliest `expected_*` number of rows.

Usage (dry-run):
  python backend/manage.py shell -c "exec(open('backend/scripts/reconcile_matrices_from_analysis.py').read())"
Apply (destructive):
  PowerShell:
    $env:APPLY='true'; python backend/manage.py shell -c "exec(open('backend/scripts/reconcile_matrices_from_analysis.py').read())"

The script:
- reads the latest `promo_matrix_expectations_*.csv` in repo root
- for each user where extra_five>0 or extra_three>0, finds matrix rows within lookback window (DAYS env, default 60)
- keeps earliest `expected_*` rows and marks the rest for deletion
- writes a backup CSV before deleting
"""
import os
import csv
from datetime import datetime, timedelta
from django.utils import timezone
from glob import glob

DAYS = int(os.environ.get('DAYS', '60'))
APPLY = str(os.environ.get('APPLY', '')).lower() in ('1', 'true', 'yes')


def find_latest_analysis_csv():
    files = sorted(glob('promo_matrix_expectations_*.csv'), reverse=True)
    return files[0] if files else None


def run():
    analysis_csv = find_latest_analysis_csv()
    if not analysis_csv:
        print('No analysis CSV found. Run analyze_promo_matrix_expectations.py first.')
        return

    print('Using analysis file:', analysis_csv)

    # Read analysis rows where extra_five>0 or extra_three>0
    to_action = []
    with open(analysis_csv, 'r', encoding='utf-8') as f:
        rdr = csv.DictReader(f)
        for r in rdr:
            extra_five = int(float(r.get('extra_five') or 0))
            extra_three = int(float(r.get('extra_three') or 0))
            if extra_five > 0 or extra_three > 0:
                to_action.append(r)

    if not to_action:
        print('No users with extras found in analysis CSV.')
        return

    from business.models import AutoPoolAccount

    cutoff = timezone.now() - timedelta(days=DAYS)

    delete_rows = []
    for r in to_action:
        uid = int(r['user_id'])
        expected_five = int(float(r.get('expected_five') or 0))
        expected_three = int(float(r.get('expected_three') or 0))

        # FIVE_150
        five_qs = list(AutoPoolAccount.objects.filter(owner_id=uid, pool_type='FIVE_150', created_at__gte=cutoff).values('id','owner_id','pool_type','source_type','source_id','created_at').order_by('created_at'))
        if len(five_qs) > expected_five:
            extras = five_qs[expected_five:]
            for ex in extras:
                delete_rows.append(ex)

        # THREE_150
        three_qs = list(AutoPoolAccount.objects.filter(owner_id=uid, pool_type='THREE_150', created_at__gte=cutoff).values('id','owner_id','pool_type','source_type','source_id','created_at').order_by('created_at'))
        if len(three_qs) > expected_three:
            extras = three_qs[expected_three:]
            for ex in extras:
                delete_rows.append(ex)

    if not delete_rows:
        print('No rows to delete after reconciling.')
        return

    ts = datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')
    backup_path = os.path.join(os.getcwd(), f'reconcile_duplicates_backup_{ts}.csv')
    with open(backup_path, 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=['id','owner_id','pool_type','source_type','source_id','created_at'])
        w.writeheader()
        for r in delete_rows:
            w.writerow({k: (r.get(k) or '') for k in w.fieldnames})
    print(f'Backup of {len(delete_rows)} rows written to: {backup_path}')

    # Show sample
    for r in delete_rows[:20]:
        print(r)

    if not APPLY:
        print('\nDry-run complete. Set APPLY=true to actually delete these rows.')
        return

    ids_to_delete = [int(r['id']) for r in delete_rows]
    print(f'Deleting {len(ids_to_delete)} rows...')
    try:
        with transaction.atomic():
            from django.db import transaction
            deleted, _ = AutoPoolAccount.objects.filter(id__in=ids_to_delete).delete()
        print(f'Deleted {deleted} objects.')
        print('If needed, restore from:', backup_path)
    except Exception as e:
        print('Error deleting rows:', e)


if __name__ == '__main__':
    run()
