# Generated by Django 6.0.2 on 2026-05-14 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CANONICAL_PERMISSION_DEFS = [
    ("dashboard.read", "Dashboard", "Read dashboard"),
    ("users.read", "Users", "Read users"),
    ("users.write", "Users", "Create and update users"),
    ("users.delete", "Users", "Delete users"),
    ("roles.read", "Roles", "Read roles"),
    ("roles.manage", "Roles", "Manage roles"),
    ("permissions.read", "Permissions", "Read permissions"),
    ("permissions.manage", "Permissions", "Manage permissions"),
    ("withdrawals.read", "Withdrawals", "Read withdrawals"),
    ("withdrawals.approve", "Withdrawals", "Approve withdrawals"),
    ("wallet.read", "Wallet", "Read wallet data"),
    ("wallet.adjust", "Wallet", "Adjust wallet balances"),
    ("kyc.read", "KYC", "Read KYC"),
    ("kyc.approve", "KYC", "Approve KYC"),
    ("reports.read", "Reports", "Read reports"),
    ("settings.manage", "Settings", "Manage settings"),
    ("support.read", "Support", "Read support tickets"),
    ("support.write", "Support", "Respond to support tickets"),
    ("ecoupons.read", "E-Coupons", "Read e-coupons"),
    ("ecoupons.write", "E-Coupons", "Manage e-coupons"),
    ("promo.read", "Promo", "Read promo/package approvals"),
    ("promo.approve", "Promo", "Approve promo/package requests"),
    ("autopool.read", "Autopool", "Read autopool data"),
    ("commissions.read", "Commissions", "Read commissions"),
    ("commissions.manage", "Commissions", "Manage commissions"),
]


def seed_canonical_permissions(apps, schema_editor):
    Permission = apps.get_model("adminapi", "Permission")
    Role = apps.get_model("adminapi", "Role")
    for code, module, name in CANONICAL_PERMISSION_DEFS:
        Permission.objects.update_or_create(
            code=code,
            defaults={"module": module, "name": name, "label": name},
        )
    Role.objects.update_or_create(
        name="Super Admin",
        defaults={"is_super": True, "is_system": True, "description": "Full administrative access."},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_links', to='adminapi.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adminapi_user_roles',
                'indexes': [models.Index(fields=['user', 'role'], name='adminapi_us_user_id_37827c_idx')],
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.RunPython(seed_canonical_permissions, migrations.RunPython.noop),
    ]
