apiVersion: v1
kind: Namespace
metadata:
  name: trikonekt-prod
  labels:
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: trikonekt-staging
  labels:
    environment: staging
