# Generated by Django 5.2.7 on 2025-10-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_dashboardcard_luckydrawsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='role',
            field=models.CharField(blank=True, help_text='Optional: restrict this card to a specific role (user/employee/agency)', max_length=20),
        ),
    ]
