# Generated by Django 5.2.7 on 2025-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_homecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='agency_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='agency_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='coupon_purchaser_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='referral_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='referral_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='tr_referral_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
