# Generated by Django 5.2.7 on 2025-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_luckydrawsubmission_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='tr_emp_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
