# Generated by Django 5.2.7 on 2025-10-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_luckydrawsubmission_tr_emp_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='agency_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='agency_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='agency_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_lucky_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='assigned_tre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lucky_draws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('TRE_APPROVED', 'TRE Approved'), ('TRE_REJECTED', 'TRE Rejected'), ('AGENCY_APPROVED', 'Agency Approved'), ('AGENCY_REJECTED', 'Agency Rejected')], db_index=True, default='SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='tre_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='tre_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='tre_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tre_lucky_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
