# Generated by Django 5.2.7 on 2025-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_agencycouponquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckycouponassignment',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
