# Generated by Django 5.2.7 on 2025-11-06 10:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0012_luckycouponassignment_sold_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcard',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/cards/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='homecard',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/homecard/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/resumes/'),
        ),
        migrations.AlterField(
            model_name='luckydrawsubmission',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/lucky_draw/'),
        ),
    ]
