# Generated by Django 5.2.7 on 2025-12-07 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0014_luckydraweligibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='admin_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luckydrawsubmission',
            name='admin_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_lucky_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='luckydrawsubmission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('TRE_APPROVED', 'TRE Approved'), ('TRE_REJECTED', 'TRE Rejected'), ('AGENCY_APPROVED', 'Agency Approved'), ('AGENCY_REJECTED', 'Agency Rejected'), ('ADMIN_APPROVED', 'Admin Approved'), ('ADMIN_REJECTED', 'Admin Rejected')], db_index=True, default='SUBMITTED', max_length=20),
        ),
        migrations.CreateModel(
            name='LuckySpinDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SCHEDULED', 'SCHEDULED'), ('LOCKED', 'LOCKED'), ('LIVE', 'LIVE'), ('ENDED', 'ENDED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='DRAFT', max_length=16)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('locked', models.BooleanField(default=False, help_text='Freeze config and winners before going live')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spin_draws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LuckySpinAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('WIN', 'WIN'), ('LOSE', 'LOSE')], max_length=8)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_attempts', to=settings.AUTH_USER_MODEL)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='uploads.luckyspindraw')),
            ],
            options={
                'ordering': ['-spun_at', '-id'],
                'indexes': [models.Index(fields=['draw', 'user'], name='uploads_luc_draw_id_06ccbf_idx'), models.Index(fields=['user', 'spun_at'], name='uploads_luc_user_id_5889cf_idx')],
                'unique_together': {('draw', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LuckySpinWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('prize_title', models.CharField(blank=True, default='', max_length=200)),
                ('prize_description', models.TextField(blank=True, default='')),
                ('prize_type', models.CharField(choices=[('INFO', 'Informational'), ('WALLET', 'Wallet Credit'), ('COUPON', 'Coupon')], default='INFO', max_length=16)),
                ('prize_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prize_meta', models.JSONField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_source', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='uploads.luckyspindraw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['draw', 'user'], name='uploads_luc_draw_id_b94712_idx')],
                'unique_together': {('draw', 'user')},
            },
        ),
    ]
