# Generated by Django 5.2.7 on 2026-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0016_herobanner_promotion_categorybanner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorybanner',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='categorybanner',
            name='key',
            field=models.SlugField(unique=True),
        ),
    ]
