# Generated by Django 5.2.7 on 2025-10-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_country_iso3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='iso3',
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
