# Generated by Django 5.2.7 on 2025-10-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_purchaserequest_payment_method'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banneritem',
            new_name='market_bann_banner__16de9b_idx',
            old_name='market_ban_banner__b6f3a7_idx',
        ),
    ]
