# Generated by Django 5.2.7 on 2025-12-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_merchantprofile_merchantshop_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_reward_redeem_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='reward_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
