# Generated by Django 5.2.7 on 2025-12-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_customuser_category_rewardpointsaccount_and_more'),
        ('market', '0009_product_max_reward_redeem_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='reward_points_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='accounts.rewardpointshold'),
        ),
    ]
