# Generated by Django 5.2.7 on 2026-01-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_alter_triapp_options_triapp_icon_triapp_sort_order'),
        ('market', '0010_purchaserequest_reward_points_hold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='tri_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='business.triapp'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['pincode'], name='market_shop_pincode_1eb60b_idx'),
        ),
    ]
