# Generated by Django 5.2.7 on 2026-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_shop_pincode_shop_tri_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='business_category',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='service_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BOTH', 'Both')], db_index=True, default='BOTH', max_length=10),
        ),
    ]
