# Generated by Django 6.0.1 on 2026-02-12 08:15

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_merchantprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('online_delivery', models.BooleanField(default=False)),
                ('offline_delivery', models.BooleanField(default=True)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/shop/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'is_active'], name='market_shop_shop_id_c033bf_idx'), models.Index(fields=['is_active', 'created_at'], name='market_shop_is_acti_d19167_idx')],
            },
        ),
    ]
