# Generated by Django 6.0.2 on 2026-08-01 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0049_rename_business_pa_invoice_41138d_idx_business_pa_invoice_690d5d_idx_and_more'),
        ('market', '0013_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='additional_images',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='business.merchantcategory'),
        ),
        migrations.AddField(
            model_name='shop',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='business.merchantsubcategory'),
        ),
    ]
