from __future__ import annotations


class WalletTypes:
    MAIN = "MAIN"
    TOTAL_EARNINGS = "TOTAL_EARNINGS"
    REDEEM_POINTS = "REDEEM_POINTS"
    COUPON_POCKET = "COUPON_POCKET"
    SELF_PACKAGE_POCKET = "SELF_PACKAGE_POCKET"
    ADD_MONEY_POCKET = "ADD_MONEY_POCKET"
    WITHDRAWAL_WALLET = "WITHDRAWAL_WALLET"
    PACKAGE_PURCHASE_COUPON = "PACKAGE_PURCHASE_COUPON"
    SHOPPING_REBIRTH = "SHOPPING_REBIRTH"
    REWARD_WALLET = "REWARD_WALLET"
    GIFT_CARD = "GIFT_CARD"
    ECOMMERCE = "ECOMMERCE"
    SYSTEM = "SYSTEM"


class FinanceCategories:
    ADD_MONEY = "ADD_MONEY"
    WITHDRAWAL = "WITHDRAWAL"
    WALLET_TRANSFER = "WALLET_TRANSFER"
    VOUCHER_CREATE = "VOUCHER_CREATE"
    VOUCHER_REDEEM = "VOUCHER_REDEEM"
    PACKAGE_PURCHASE = "PACKAGE_PURCHASE"
    MLM_INCOME = "MLM_INCOME"
    SPONSOR_INCOME = "SPONSOR_INCOME"
    MATRIX_INCOME = "MATRIX_INCOME"
    SELF_REBIRTH = "SELF_REBIRTH"
    SHOPPING_REWARD = "SHOPPING_REWARD"
    FRANCHISE_REWARD = "FRANCHISE_REWARD"
    REWARD_DISTRIBUTION = "REWARD_DISTRIBUTION"
    GST_INVOICE = "GST_INVOICE"
    ADMIN_ADJUSTMENT = "ADMIN_ADJUSTMENT"
    REFUND = "REFUND"
    SETTLEMENT = "SETTLEMENT"
    


class FinanceStatuses:
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REVERSED = "REVERSED"
    CANCELLED = "CANCELLED"


class ApprovalStatuses:
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class LedgerDirections:
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"
