# Generated by Django 5.2.7 on 2025-10-29 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_remove_country_iso3_alter_country_iso2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, db_index=True, editable=False, max_length=6, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('business_category', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('sponsor_id', models.CharField(blank=True, max_length=64)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=10)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('forwarded', 'Forwarded'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_registrations', to='locations.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_registrations', to='locations.country')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_business_enquiries', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_business_registrations', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_registrations', to='locations.state')),
            ],
            options={
                'verbose_name': 'Business Registration',
                'verbose_name_plural': 'Business Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
