# Generated by Django 5.2.7 on 2025-10-30 05:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_coupon_value', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
                ('enable_pool_distribution', models.BooleanField(default=True)),
                ('l1_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('l2_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('l3_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('l4_percent', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('l5_percent', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commission Config',
                'verbose_name_plural': 'Commission Config',
            },
        ),
        migrations.CreateModel(
            name='AutoPoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_key', models.CharField(db_index=True, max_length=150)),
                ('entry_amount', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], db_index=True, default='ACTIVE', max_length=16)),
                ('level', models.PositiveIntegerField(db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='business.autopoolaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username_key', 'status'], name='business_au_usernam_3b96a6_idx')],
            },
        ),
    ]
