# Generated by Django 5.2.7 on 2025-11-03 17:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_extend_commissionconfig_geo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('key', models.CharField(choices=[('TR_ID', 'TR_ID'), ('WG_ID', 'WG_ID'), ('ASIA_PAY_ID', 'ASIA_PAY_ID'), ('DM_ACCOUNT', 'DM_ACCOUNT')], db_index=True, max_length=32)),
                ('today_value', models.IntegerField(default=0)),
                ('total_value', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_key', models.CharField(db_index=True, max_length=32)),
                ('coupons_spent', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('PRIME_150_ACTIVE', 'PRIME_150_ACTIVE'), ('PRIME_150_REDEEM', 'PRIME_150_REDEEM'), ('GLOBAL_50', 'GLOBAL_50'), ('SELF_50', 'SELF_50'), ('PRODUCT_PRIME', 'PRODUCT_PRIME'), ('PRODUCT_GLOBAL_50', 'PRODUCT_GLOBAL_50')], db_index=True, max_length=32)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='autopoolaccount',
            name='pool_type',
            field=models.CharField(choices=[('FIVE_150', 'FIVE_150'), ('THREE_150', 'THREE_150'), ('THREE_50', 'THREE_50')], db_index=True, default='THREE_150', max_length=16),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='active_direct_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='active_self_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='enable_geo_distribution_on_activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='five_matrix_levels',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='five_matrix_percents_json',
            field=models.JSONField(default=list, help_text='List of percents for 5-matrix levels (length=five_matrix_levels)'),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='global_activation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='prime_activation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='product_opens_prime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='redeem_credit_amount_150',
            field=models.DecimalField(decimal_places=2, default=Decimal('140.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='rewards_weights_json',
            field=models.JSONField(default=dict, help_text='e.g., {"prime":1,"global":1,"coupon_submission":1,"active":1,"redeem":0}'),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='three_matrix_levels',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='three_matrix_percents_json',
            field=models.JSONField(default=list, help_text='List of percents for 3-matrix levels (length=three_matrix_levels)'),
        ),
        migrations.AddIndex(
            model_name='autopoolaccount',
            index=models.Index(fields=['pool_type', 'status'], name='business_au_pool_ty_71980b_idx'),
        ),
        migrations.AddField(
            model_name='reportmetric',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_activations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reportmetric',
            constraint=models.UniqueConstraint(fields=('date', 'key'), name='uniq_reportmetric_date_key'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['user', 'reward_key'], name='business_re_user_id_9320b8_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['status', 'requested_at'], name='business_re_status_71c120_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionactivation',
            index=models.Index(fields=['user', 'package'], name='business_su_user_id_2813e9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionactivation',
            index=models.Index(fields=['source_type', 'source_id'], name='business_su_source__4f039f_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionactivation',
            constraint=models.UniqueConstraint(fields=('user', 'package', 'source_type', 'source_id'), name='uniq_activation_user_pkg_source'),
        ),
    ]
