# Generated by Django 5.2.7 on 2025-11-03 18:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_reportmetric_rewardprogress_rewardredemption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionconfig',
            name='autopool_trigger_on_direct_referral',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='enable_franchise_on_join',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='enable_franchise_on_purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='five_matrix_amounts_json',
            field=models.JSONField(default=list, help_text='Fixed rupees per level for 5-matrix (length 6)'),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='franchise_fixed_json',
            field=models.JSONField(default=dict, help_text='e.g., {"sub_franchise":15,"pincode":4,"pincode_coord":2,"district":1,"district_coord":1,"state":1,"state_coord":1}'),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='referral_join_fixed_json',
            field=models.JSONField(default=dict, help_text='e.g., {"direct":5,"l1":2,"l2":1,"l3":1,"l4":0.5,"l5":0.5}'),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='three_matrix_amounts_json',
            field=models.JSONField(default=list, help_text='Fixed rupees per level for 3-matrix (length 15)'),
        ),
        migrations.CreateModel(
            name='ReferralJoinPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_join_payout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FranchisePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('registration', 'registration'), ('purchase', 'purchase')], db_index=True, max_length=16)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['trigger', 'created_at'], name='business_fr_trigger_90c22c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_new', 'trigger', 'source_type', 'source_id'), name='uniq_franchise_payout_marker')],
            },
        ),
        migrations.CreateModel(
            name='UserMatrixProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_type', models.CharField(choices=[('FIVE_150', 'FIVE_150'), ('THREE_150', 'THREE_150'), ('THREE_50', 'THREE_50')], db_index=True, max_length=16)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('level_reached', models.PositiveIntegerField(default=0)),
                ('per_level_counts', models.JSONField(blank=True, default=dict)),
                ('per_level_earned', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'pool_type'], name='business_us_user_id_dc8745_idx')],
                'unique_together': {('user', 'pool_type')},
            },
        ),
    ]
