# Generated by Django 5.2.7 on 2025-11-03 18:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_commissionconfig_autopool_trigger_on_direct_referral_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionconfig',
            name='active_direct_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='active_self_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('SUBFRANCHISE', 'Sub-Franchise')], db_index=True, max_length=20)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('tr_registered', models.IntegerField(default=0)),
                ('wg_registered', models.IntegerField(default=0)),
                ('asia_pay_registered', models.IntegerField(default=0)),
                ('dm_account_registered', models.IntegerField(default=0)),
                ('e_coupon_issued', models.IntegerField(default=0)),
                ('physical_coupon_issued', models.IntegerField(default=0)),
                ('product_sold', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['reporter', 'date'], name='business_da_reporte_2cd398_idx'), models.Index(fields=['role', 'date'], name='business_da_role_f9d116_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'date'), name='uniq_daily_report_per_user_per_date')],
            },
        ),
    ]
