# Generated by Django 5.2.7 on 2025-11-19 06:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_commissionconfig_active_direct_bonus_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionconfig',
            name='tax_company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_pool_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
    ]
