# Generated by Django 5.2.7 on 2025-11-19 07:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_commissionconfig_tax_company_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithholdingReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, db_index=True, default='LEGACY_SPLIT', max_length=32)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('withheld_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('reserved', 'reserved'), ('partial', 'partial'), ('distributed', 'distributed')], db_index=True, default='reserved', max_length=16)),
                ('breakdown', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withholding_reserves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='business_wi_user_id_5d5c5c_idx'), models.Index(fields=['source_type', 'source_id'], name='business_wi_source__de89fe_idx')],
            },
        ),
    ]
