# Generated by Django 5.2.7 on 2025-11-19 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_withholdingreserve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='withholdingreserve',
            constraint=models.UniqueConstraint(fields=('user', 'source_type', 'source_id'), name='uniq_withholding_reserve_user_source'),
        ),
    ]
