# Generated by Django 5.2.7 on 2025-11-24 08:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_withholdingreserve_uniq_withholding_reserve_user_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AgencyPackageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_assignments', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='business.package')),
            ],
            options={
                'ordering': ['-created_at', 'agency_id'],
            },
        ),
        migrations.CreateModel(
            name='AgencyPackagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('paid_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business.agencypackageassignment')),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['assignment', 'paid_at'], name='business_ag_assignm_3fd2be_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agencypackageassignment',
            index=models.Index(fields=['agency', 'package'], name='business_ag_agency__208811_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencypackageassignment',
            unique_together={('agency', 'package')},
        ),
    ]
