# Generated by Django 5.2.7 on 2025-11-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_package_agencypackageassignment_agencypackagepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If true, auto-assign to every agency by default'),
        ),
    ]
