# Generated by Django 5.2.7 on 2025-11-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_package_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionconfig',
            name='master_commission_json',
            field=models.JSONField(default=dict, help_text='Editable config for agency/employee upline splits and consumer 3/5 matrix. Keys: agency, employee, consumer_matrix_3, consumer_matrix_5, general'),
        ),
    ]
