# Generated by Django 5.2.7 on 2025-12-01 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_promopackage_promopurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='promopurchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
