# Generated by Django 5.2.7 on 2025-12-04 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_commissionconfig_reward_points_config_json'),
        ('market', '0007_alter_banner_image_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promopurchase',
            name='boxes_json',
            field=models.JSONField(blank=True, default=list, help_text='Selected box numbers for MONTHLY (1..12)'),
        ),
        migrations.AddField(
            model_name='promopurchase',
            name='delivery_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promopurchase',
            name='package_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='promopurchase',
            name='selected_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_promo_purchases', to='market.product'),
        ),
        migrations.AddField(
            model_name='promopurchase',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PromoMonthlyBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.PositiveIntegerField(db_index=True)),
                ('box_number', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_monthly_boxes', to='business.promopackage')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_boxes', to='business.promopurchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_monthly_boxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'package', 'package_number'], name='business_pr_user_id_dfc5cb_idx'), models.Index(fields=['package', 'package_number', 'box_number'], name='business_pr_package_1c8363_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'package', 'package_number', 'box_number'), name='uniq_monthly_box_user_pkg_num_box')],
            },
        ),
        migrations.CreateModel(
            name='PromoMonthlyPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_boxes', models.PositiveIntegerField(default=12)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_packages', to='business.promopackage')),
            ],
            options={
                'ordering': ['package_id', 'number'],
                'indexes': [models.Index(fields=['package', 'number', 'is_active'], name='business_pr_package_139a7e_idx')],
                'unique_together': {('package', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PromoPackageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_products', to='business.promopackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_packages', to='market.product')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['package', 'is_active', 'display_order'], name='business_pr_package_bab091_idx')],
                'unique_together': {('package', 'product')},
            },
        ),
    ]
