# Generated by Django 5.2.7 on 2025-12-06 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_promopurchase_boxes_json_promopurchase_delivery_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoEBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='uploads/ebooks/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='uploads/ebooks/covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='promopurchase',
            name='prime150_choice',
            field=models.CharField(blank=True, db_index=True, default='', help_text='For PRIME 150: EBOOK or REDEEM', max_length=16),
        ),
        migrations.CreateModel(
            name='EBookAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_accesses', to=settings.AUTH_USER_MODEL)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='business.promoebook')),
            ],
            options={
                'ordering': ['-granted_at', '-id'],
                'unique_together': {('user', 'ebook')},
            },
        ),
        migrations.CreateModel(
            name='PromoPackageEBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='business.promoebook')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks', to='business.promopackage')),
            ],
            options={
                'ordering': ['package_id', 'display_order', 'id'],
                'unique_together': {('package', 'ebook')},
            },
        ),
    ]
