# Generated by Django 5.2.7 on 2025-12-07 08:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_promoebook_promopurchase_prime150_choice_ebookaccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promopurchase',
            name='prime750_choice',
            field=models.CharField(blank=True, db_index=True, default='', help_text='For PRIME 750: PRODUCT or REDEEM or COUPON', max_length=16),
        ),
        migrations.AlterField(
            model_name='promoebook',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/ebooks/covers/'),
        ),
        migrations.AlterField(
            model_name='promoebook',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/ebooks/'),
        ),
        migrations.AlterField(
            model_name='promopurchase',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/promo_proofs/'),
        ),
    ]
