# Generated by Django 5.2.7 on 2025-12-07 08:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_promopurchase_prime750_choice_alter_promoebook_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/promo_products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='promopurchase',
            name='selected_promo_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_promo_purchases', to='business.promoproduct'),
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO business_promoproduct (id, name, description, price, image, is_active, created_at, updated_at)
            SELECT mp.id,
                   COALESCE(mp.name, CONCAT('Legacy Product #', mp.id)),
                   COALESCE(mp.description, ''),
                   COALESCE(mp.price, 0.01),
                   NULL,
                   TRUE,
                   NOW(),
                   NOW()
            FROM market_product mp
            JOIN (SELECT DISTINCT product_id FROM business_promopackageproduct WHERE product_id IS NOT NULL) mpp
              ON mpp.product_id = mp.id
            ON CONFLICT (id) DO NOTHING;
            """,
            reverse_sql="SELECT 1;",
        ),
        migrations.RunSQL(
            sql="""
            SELECT setval(
                pg_get_serial_sequence('business_promoproduct','id'),
                COALESCE((SELECT MAX(id) FROM business_promoproduct), 1),
                true
            );
            """,
            reverse_sql="SELECT 1;",
        ),
        migrations.AlterField(
            model_name='promopackageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_packages', to='business.promoproduct'),
        ),
    ]
