# Generated by Django 5.2.7 on 2025-12-08 17:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_wallettransaction_type'),
        ('business', '0019_promoproduct_promopurchase_selected_promo_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_key', models.CharField(db_index=True, max_length=32)),
                ('role_key', models.CharField(db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='autopoolaccount',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='autopoolaccount',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='autopoolaccount',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='autopoolaccount',
            index=models.Index(fields=['parent_account', 'pool_type', 'position'], name='business_au_parent__476a47_idx'),
        ),
        migrations.AddConstraint(
            model_name='autopoolaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_account__isnull', False)), fields=('parent_account', 'pool_type', 'position'), name='uniq_autopool_sibling_position'),
        ),
        migrations.AddField(
            model_name='companycommissionpayout',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_tax_benefits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycommissionpayout',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_tax_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycommissionpayout',
            name='tax_tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tax_payouts', to='accounts.wallettransaction'),
        ),
        migrations.AddIndex(
            model_name='companycommissionpayout',
            index=models.Index(fields=['tax_tx'], name='business_co_tax_tx__d66c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='companycommissionpayout',
            index=models.Index(fields=['beneficiary'], name='business_co_benefic_3b3782_idx'),
        ),
        migrations.AddIndex(
            model_name='companycommissionpayout',
            index=models.Index(fields=['pool_key', 'role_key'], name='business_co_pool_ke_c2d8fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='companycommissionpayout',
            constraint=models.UniqueConstraint(fields=('tax_tx', 'beneficiary', 'pool_key', 'role_key'), name='uniq_company_tax_payout_row'),
        ),
    ]
