# Generated by Django 5.2.7 on 2025-12-15 05:23

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_companycommissionpayout_autopoolaccount_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL key e.g., tri-holidays, tri-ev', max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_price', models.BooleanField(default=False, help_text='If false, hide product prices to users.')),
                ('allow_add_to_cart', models.BooleanField(default=False, help_text='If false, disable Add to Cart buttons.')),
                ('allow_payment', models.BooleanField(default=False, help_text='If false, disable Checkout/Payment flows.')),
                ('banner_image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/tri_apps/banners/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TRI App',
                'verbose_name_plural': 'TRI Apps',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TriAppProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/tri_apps/products/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.triapp')),
            ],
            options={
                'ordering': ['app_id', 'display_order', 'id'],
                'indexes': [models.Index(fields=['app', 'is_active', 'display_order'], name='business_tr_app_id_b40d9c_idx')],
            },
        ),
    ]
