# Generated by Django 5.2.7 on 2025-12-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_triapp_triappproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='triappproduct',
            name='max_reward_points_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max % of line total redeemable via reward points', max_digits=5),
        ),
    ]
