# Generated by Django 5.2.7 on 2025-12-20 05:07

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_triappproduct_max_reward_points_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/agency_package_qr/'),
        ),
        migrations.AddField(
            model_name='package',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AgencyPackagePaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('method', models.CharField(db_index=True, default='UPI', max_length=16)),
                ('utr', models.CharField(blank=True, default='', help_text='UPI Reference/UTR', max_length=100)),
                ('payment_proof', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/agency_package_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], db_index=True, default='PENDING', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_package_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agency_package_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='business.agencypackageassignment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_payment_requests', to='business.package')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='business_ag_status_eced0e_idx'), models.Index(fields=['agency', 'status'], name='business_ag_agency__6df8a1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('assignment',), name='uniq_pending_request_per_assignment')],
            },
        ),
    ]
