# Generated by Django 5.2.7 on 2026-01-06 15:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_package_payment_qr_package_upi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionconfig',
            name='monthly_759_open_once',
            field=models.BooleanField(default=True, help_text='If true, 5/3 matrices open only on the first 759 purchase'),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='prime_750_redeem_mode',
            field=models.CharField(default='units_and_wallet', help_text='units_and_wallet | wallet_only', max_length=24),
        ),
        migrations.AddField(
            model_name='commissionconfig',
            name='prime_750_units',
            field=models.PositiveIntegerField(default=5, help_text='How many 150-units to open for PRIME 750'),
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='redeem_credit_amount_150',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10),
        ),
    ]
