# Generated by Django - custom migration to enforce matrix integrity and speed placement scans
from django.db import migrations, models
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0024_commissionconfig_monthly_759_open_once_and_more"),
    ]

    operations = [
        # Deterministic parent scans for BFS placement
        migrations.AddIndex(
            model_name="autopoolaccount",
            index=models.Index(fields=["pool_type", "level", "id"], name="idx_ap_pool_level_id"),
        ),
        # Speed child lookups under locked parent
        migrations.AddIndex(
            model_name="autopoolaccount",
            index=models.Index(fields=["parent_account", "pool_type", "status"], name="idx_ap_parent_pool_status"),
        ),
        # Ensure exactly one sentinel root (parent=NULL, level=0) per pool_type
        migrations.AddConstraint(
            model_name="autopoolaccount",
            constraint=models.UniqueConstraint(
                fields=["pool_type"],
                condition=models.Q(parent_account__isnull=True, level=0),
                name="uniq_ap_root_per_pool",
            ),
        ),
        # Enforce position range by pool width for non-root rows.
        # Root rows (parent=NULL) are exempt; legacy data with parent=NULL/level>0 remain unaffected.
        migrations.AddConstraint(
            model_name="autopoolaccount",
            constraint=models.CheckConstraint(
                name="chk_ap_position_within_width",
                condition=(
                    # FIVE_150 children must be in 1..5
                    (
                        models.Q(pool_type="FIVE_150") &
                        models.Q(parent_account__isnull=False) &
                        models.Q(position__gte=1) &
                        models.Q(position__lte=5)
                    )
                    |
                    # THREE_* children must be in 1..3
                    (
                        models.Q(pool_type__in=["THREE_150", "THREE_50"]) &
                        models.Q(parent_account__isnull=False) &
                        models.Q(position__gte=1) &
                        models.Q(position__lte=3)
                    )
                    |
                    # Exempt all roots (parent=NULL)
                    models.Q(parent_account__isnull=True)
                ),
            ),
        ),
    ]
