# Generated by Django 5.2.7 on 2026-01-16 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_matrix_constraints_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo759Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=16)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-active_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PromoProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DISPATCHED', 'DISPATCHED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='autopoolaccount',
            name='uniq_ap_root_per_pool',
        ),
        migrations.RemoveConstraint(
            model_name='autopoolaccount',
            name='chk_ap_position_within_width',
        ),
        migrations.RemoveIndex(
            model_name='autopoolaccount',
            name='idx_ap_pool_level_id',
        ),
        migrations.RemoveIndex(
            model_name='autopoolaccount',
            name='idx_ap_parent_pool_status',
        ),
        migrations.AddField(
            model_name='promo759subscription',
            name='promo_purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_759', to='business.promopurchase'),
        ),
        migrations.AddField(
            model_name='promo759subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_759_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promoproductorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='business.promoproduct'),
        ),
        migrations.AddField(
            model_name='promoproductorder',
            name='promo_purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='business.promopurchase'),
        ),
        migrations.AddField(
            model_name='promoproductorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_product_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
