# Generated by Django 5.2.7 on 2026-01-18 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_promo759subscription_promoproductorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RootConsumerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_root_consumer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Root Consumer Config',
                'verbose_name_plural': 'Root Consumer Config',
            },
        ),
    ]
