# Generated by Django 5.2.7 on 2026-01-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_rootconsumerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Merchant Category',
                'verbose_name_plural': 'Merchant Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='business.merchantcategory'),
        ),
        migrations.CreateModel(
            name='MerchantSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='business.merchantcategory')),
            ],
            options={
                'verbose_name': 'Merchant Subcategory',
                'verbose_name_plural': 'Merchant Subcategories',
                'ordering': ['category_id', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='business.merchantsubcategory'),
        ),
        migrations.AddConstraint(
            model_name='merchantsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_merchant_subcategory_per_category'),
        ),
    ]
