# Generated by Django 5.2.7 on 2026-01-21 15:32

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_merchantcategory_businessregistration_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triapp',
            options={'ordering': ['sort_order', 'slug'], 'verbose_name': 'TRI App', 'verbose_name_plural': 'TRI Apps'},
        ),
        migrations.AddField(
            model_name='triapp',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/tri_apps/icons/'),
        ),
        migrations.AddField(
            model_name='triapp',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
