# Generated by Django 6.0.1 on 2026-01-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_alter_triapp_options_triapp_icon_triapp_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantcategory',
            name='audience',
            field=models.CharField(choices=[('CONSUMER', 'CONSUMER'), ('MERCHANT', 'MERCHANT')], db_index=True, default='CONSUMER', max_length=16),
        ),
        migrations.AddField(
            model_name='merchantsubcategory',
            name='audience',
            field=models.CharField(choices=[('CONSUMER', 'CONSUMER'), ('MERCHANT', 'MERCHANT')], db_index=True, default='CONSUMER', max_length=16),
        ),
    ]
