# Generated by Django 5.2.10 on 2026-01-30 17:38

from django.conf import settings
from django.db import migrations, models

def backfill_user_entry_index(apps, schema_editor):
    """
    Populate unique, sequential user_entry_index per (owner, pool_type) ordered by id.
    This prepares existing data so the unique constraint can be created.
    """
    Auto = apps.get_model('business', 'AutoPoolAccount')
    # Order by owner, pool, id to assign stable ascending indices
    qs = Auto.objects.all().order_by('owner_id', 'pool_type', 'id')
    cur_owner = None
    cur_pool = None
    idx = 0
    batch = []
    # iterator() to avoid loading entire table in memory
    for a in qs.iterator():
        key = (a.owner_id, a.pool_type)
        if key != (cur_owner, cur_pool):
            cur_owner, cur_pool = key
            idx = 1
        else:
            idx += 1
        # Only set when different to avoid unnecessary writes
        if getattr(a, 'user_entry_index', 0) != idx:
            a.user_entry_index = idx
            batch.append(a)
            if len(batch) >= 1000:
                Auto.objects.bulk_update(batch, ['user_entry_index'])
                batch = []
    if batch:
        Auto.objects.bulk_update(batch, ['user_entry_index'])


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_merchantcategory_audience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autopoolaccount',
            name='user_entry_index',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        # Backfill before adding the uniqueness constraint
        migrations.RunPython(backfill_user_entry_index, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='autopoolaccount',
            constraint=models.UniqueConstraint(fields=('owner', 'pool_type', 'user_entry_index'), name='uniq_user_entry_index_per_user_pool'),
        ),
    ]
