# Generated by Django 6.0.1 on 2026-02-10 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_autopoolaccount_user_entry_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='autopoolaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_account__isnull', True)), fields=('pool_type',), name='uniq_single_sentinel_per_pool'),
        ),
    ]
