# Generated by Django 6.0.2 on 2026-04-27 13:12

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_autopool_backfill_speed_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessregistration',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='businessregistration',
            name='service_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BOTH', 'Both')], db_index=True, default='BOTH', max_length=16),
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='withdrawals_end_time',
            field=models.TimeField(default=business.models._default_withdrawals_end_time),
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='withdrawals_start_time',
            field=models.TimeField(default=business.models._default_withdrawals_start_time),
        ),
    ]
