# Generated by Django 6.0.2 on 2026-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_team_consumer_dashboard_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubbleWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='hubble', max_length=32)),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('transaction_reference_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('x_verify', models.CharField(blank=True, default='', max_length=256)),
                ('raw_body', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('process_status', models.CharField(db_index=True, default='PENDING', max_length=16)),
                ('process_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'event_type', 'received_at'], name='business_hu_provide_e39642_idx'), models.Index(fields=['transaction_reference_id', 'status'], name='business_hu_transac_73eaee_idx')],
            },
        ),
    ]
