# Generated by Django 6.0.2 on 2026-04-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_hubble_webhooks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubblewebhookevent',
            name='process_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.CreateModel(
            name='HubbleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='hubble', max_length=32)),
                ('transaction_reference_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('hubble_user_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_webhook_received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_last_event_for_transactions', to='business.hubblewebhookevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubble_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['provider', 'status', 'updated_at'], name='business_hu_provide_95fc2c_idx'), models.Index(fields=['user', 'status', 'updated_at'], name='business_hu_user_id_03922b_idx'), models.Index(fields=['hubble_user_id', 'updated_at'], name='business_hu_hubble__e2514f_idx')],
            },
        ),
    ]
