# Generated by Django 6.0.2 on 2026-05-02 06:26

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_hubble_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamconsumertopachiever',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='team_consumer/top_achievers/'),
        ),
        migrations.AlterField(
            model_name='teamconsumerwishingbanner',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='team_consumer/wishing_banners/'),
        ),
    ]
