# Generated by Django 6.0.2 on 2026-05-03 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_alter_teamconsumertopachiever_photo_and_more'),
        ('market', '0013_shopproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promopurchase',
            name='tri_app_slug',
            field=models.SlugField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='promopurchase',
            name='tri_product_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='promopurchase',
            index=models.Index(fields=['tri_app_slug', 'status', 'requested_at'], name='business_pr_tri_app_fcb34d_idx'),
        ),
    ]
