# State-only migration for Django-generated index-name drift.
#
# A normal RenameIndex was generated by makemigrations, but it failed on this
# database because the old physical index name did not exist. Keep the migration
# state aligned with models without running SQL against the database.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0045_unique_educational_video_per_rank"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="promopurchase",
                    new_name="business_pr_payment_f569cc_idx",
                    old_name="business_pro_payment_67e26b_idx",
                ),
            ],
        ),
    ]
