# Generated by Django 6.0.5 on 2026-07-19 16:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0048_invoice_settings_package_invoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='packageinvoice',
            new_name='business_pa_invoice_690d5d_idx',
            old_name='business_pa_invoice_41138d_idx',
        ),
        migrations.AddField(
            model_name='teamconsumereducationalvideo',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/invoice/'),
        ),
    ]
