# Generated by Django 5.2.7 on 2025-10-27 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('campaign', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('SOLD', 'SOLD'), ('REVOKED', 'REVOKED')], default='ASSIGNED', max_length=20)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='coupons.coupon')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(db_index=True, max_length=64)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='uploads/coupon_submissions/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('EMPLOYEE_APPROVED', 'EMPLOYEE_APPROVED'), ('AGENCY_APPROVED', 'AGENCY_APPROVED'), ('REJECTED', 'REJECTED')], db_index=True, default='SUBMITTED', max_length=20)),
                ('employee_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee_comment', models.TextField(blank=True)),
                ('agency_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('agency_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_reviews', to=settings.AUTH_USER_MODEL)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_submissions', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='coupons.coupon')),
                ('employee_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='coupons_cou_status_de7e15_idx'), models.Index(fields=['pincode'], name='coupons_cou_pincode_a6f838_idx'), models.Index(fields=['coupon'], name='coupons_cou_coupon__3338c3_idx')],
            },
        ),
    ]
