# Generated by Django 5.2.7 on 2025-10-27 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issued_channel', models.CharField(choices=[('physical', 'Physical'), ('e_coupon', 'E-Coupon')], default='physical', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ASSIGNED', 'ASSIGNED'), ('SOLD', 'SOLD'), ('REDEEMED', 'REDEEMED'), ('REVOKED', 'REVOKED')], db_index=True, default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_codes', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='coupons.coupon')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='couponsubmission',
            name='code_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='coupons.couponcode'),
        ),
        migrations.AddIndex(
            model_name='couponsubmission',
            index=models.Index(fields=['coupon_code'], name='coupons_cou_coupon__21e519_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['status'], name='coupons_cou_status_e83e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['coupon'], name='coupons_cou_coupon__a4317e_idx'),
        ),
    ]
