# Generated by Django 5.2.7 on 2025-10-28 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_couponcode_couponsubmission_code_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='assigned_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_codes_agency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='serial',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='value',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=8),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ASSIGNED_AGENCY', 'ASSIGNED_AGENCY'), ('ASSIGNED_EMPLOYEE', 'ASSIGNED_EMPLOYEE'), ('SOLD', 'SOLD'), ('REDEEMED', 'REDEEMED'), ('REVOKED', 'REVOKED')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agency', 'Agency'), ('employee', 'Employee')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('paid', 'Paid'), ('reversed', 'Reversed')], db_index=True, default='earned', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='coupons.couponcode')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='coupons.couponsubmission')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text="Code prefix, e.g. 'LC'", max_length=20)),
                ('serial_start', models.PositiveIntegerField()),
                ('serial_end', models.PositiveIntegerField()),
                ('serial_width', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='coupons.coupon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_audits', to=settings.AUTH_USER_MODEL)),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='coupons.couponcode')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='coupons.couponsubmission')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='coupons.couponbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='couponcode',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='coupons.couponbatch'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['batch'], name='coupons_cou_batch_i_e7da3b_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['serial'], name='coupons_cou_serial_c9c00c_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['role', 'status'], name='coupons_com_role_7bd7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action'], name='coupons_aud_action_931ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['created_at'], name='coupons_aud_created_edc81b_idx'),
        ),
    ]
