# Generated by Django 5.2.7 on 2025-11-14 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_couponcode_assigned_agency_couponcode_serial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='assigned_consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['assigned_consumer'], name='coupons_cou_assigne_1d0f53_idx'),
        ),
    ]
