# Generated by Django 5.2.7 on 2025-11-18 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_couponcode_assigned_consumer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponsubmission',
            name='consumer_tr_username',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='couponsubmission',
            name='tr_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_tr_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponsubmission',
            name='tr_username',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='couponsubmission',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
