# Generated by Django 5.2.7 on 2025-11-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_couponsubmission_consumer_tr_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECouponPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('upi_qr_image', models.ImageField(blank=True, null=True, upload_to='uploads/ecoupon_payment/')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('payee_name', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECouponProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enable_consumer', models.BooleanField(default=True)),
                ('enable_agency', models.BooleanField(default=True)),
                ('enable_employee', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_per_order', models.PositiveIntegerField(blank=True, null=True)),
                ('display_title', models.CharField(max_length=150)),
                ('display_desc', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_products', to='coupons.coupon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECouponOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_at_purchase', models.CharField(max_length=20)),
                ('denomination_snapshot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_proof_file', models.FileField(blank=True, null=True, upload_to='uploads/ecoupon_orders/')),
                ('utr', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='SUBMITTED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('allocated_count', models.PositiveIntegerField(default=0)),
                ('allocated_sample_codes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecoupon_orders', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ecoupon_orders', to=settings.AUTH_USER_MODEL)),
                ('payment_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.ecouponpaymentconfig')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='coupons.ecouponproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ecouponproduct',
            index=models.Index(fields=['is_active'], name='coupons_eco_is_acti_f9bfff_idx'),
        ),
        migrations.AddIndex(
            model_name='ecouponproduct',
            index=models.Index(fields=['denomination'], name='coupons_eco_denomin_0f9235_idx'),
        ),
        migrations.AddIndex(
            model_name='ecouponorder',
            index=models.Index(fields=['status'], name='coupons_eco_status_761f88_idx'),
        ),
        migrations.AddIndex(
            model_name='ecouponorder',
            index=models.Index(fields=['buyer'], name='coupons_eco_buyer_i_eb80ae_idx'),
        ),
    ]
