# Generated by Django 5.2.7 on 2025-12-03 17:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_ecouponpaymentconfig_ecouponproduct_ecouponorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecouponorder',
            name='payment_proof_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/ecoupon_orders/'),
        ),
        migrations.AlterField(
            model_name='ecouponpaymentconfig',
            name='upi_qr_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/ecoupon_payment/'),
        ),
    ]
