# Generated by Django 5.2.7 on 2025-12-12 18:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_alter_ecouponorder_payment_proof_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsubmission',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/coupon_submissions/'),
        ),
    ]
