# Generated by Django 5.2.7 on 2025-12-19 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_alter_couponsubmission_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyDrawEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lucky_draw_eligibilities', to='coupons.couponcode')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lucky_draw_eligibilities', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_lucky_draw_eligibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='coupons_luc_user_id_c3c5c5_idx'), models.Index(fields=['coupon'], name='coupons_luc_coupon__88d2d4_idx'), models.Index(fields=['value'], name='coupons_luc_value_a50617_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'coupon', 'value'), name='uniq_lucky_first_purchase_per_value_per_season')],
            },
        ),
    ]
