# Generated by Django 5.2.7 on 2026-01-06 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_luckydraweligibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['issued_channel', 'value', 'status', 'assigned_agency', 'assigned_employee', 'assigned_consumer', 'serial'], name='coupons_cou_issued__5c9e40_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['issued_channel', 'status', 'serial'], name='coupons_cou_issued__dc35bb_idx'),
        ),
        migrations.AddIndex(
            model_name='couponcode',
            index=models.Index(fields=['issued_channel', 'value', 'status'], name='coupons_cou_issued__73d91b_idx'),
        ),
    ]
